
title: "Tab-Distillation: Dataset Distillation on Tabular Data for Outlier Detection"
description: "Landing page for the research paper on dataset distillation for outlier detection in tabular data."
theme: jekyll-theme-minimal
